### ISSUE TITLE
punycode deprecation warning in node 21

### ISSUE THREAD

**Issue by twelvelabs** [Redocly/redocly-cli#1332]
**Describe the bug**

I'm getting a node depreciation warning whenever I run redocly on node v21. Looks like it's coming from `whatwg-url`. They appear to have fixed it in [v13.0.0](https://github.com/jsdom/whatwg-url/issues/261#issuecomment-1787323662).

**To Reproduce**

```
$ node --version
v21.1.0

$ redocly --version
1.4.1

$ NODE_OPTIONS='--trace-deprecation' redocly lint
(node:48436) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@redocly/cli/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
validating /src/schemas/default/openapi.yaml...
/src/schemas/default/openapi.yaml: validated in 3ms

Woohoo! Your API description is valid. 🎉
```

**Expected behavior**

No depreciation warning 😄.

**Redocly Version(s)**

`1.4.1`

**`Node.js` Version(s)**

`v21.1.0`

**Comment by tatomyr** [comment]
Thanks for reporting! We'll take a look at this.

**Comment by bentcoder** [comment]
Same here.

```
node: v21.2.0
npm: 10.2.4
yarn: 1.22.19
```

To reproduce.

```
FROM node:alpine3.18
ENV REDOCLY_TELEMETRY off
ENV NODE_OPTIONS --trace-deprecation
RUN npm install -g npm@10.2.4
RUN npm install -g @redocly/cli
WORKDIR /api
COPY spec.yaml /api
RUN redocly lint spec.yaml
```

**Comment by tatomyr** [comment]
The issue comes from AJV:
```

┬ @redocly/openapi-core@1.6.0 -> ./packages/core
└─┬ @redocly/ajv@8.11.0
  └─┬ uri-js@4.4.1
    └── punycode@2.1.1

```

**Comment by RomanHotsiy** [comment]
We need to update our fork to the upstream version I think.

**Comment by domdomegg** [comment]
See https://github.com/garycourt/uri-js/pull/95

**Comment by drwpow** [comment]
Update: problem also exists in Node 22 (current version)

**Comment by piotr-cz** [comment]
The issue also comes up from outdated `tr46` package.

My workaround in package.json

```json
{
  "overrides": {
    "@redocly/cli": {
      "uri-js": "npm:uri-js-replace",
      "whatwg-url": "^14.0.0"
    }
  }
}
```

It seems that updating project dependencies (`ajv`, `node-fetch`) should fix the problem

**Comment by DmitryAnansky** [comment]
@tatomyr / @lornajane 
This issue should be fixed in @redocly/ajv "version": "8.11.2",
But it will take effect with the next version of CLI and Spot release.

**Comment by piotr-cz** [comment]
The `uri-js` package has been replaced by `uri-js-replace` in recent versions of `@redocly/cli` dependencies, but the issue persist due to `whatwg-url@5.0.0`

**Comment by adamaltman** [comment]
Can we increase the priority of this (not because it causes any functional issue but because of pure aesthetics)? 

```
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by tatomyr** [comment]
@adamaltman sure. @DmitryAnansky was about to pick it up the next week.

**Comment by piotr-cz** [comment]
Given that `node-fetch` (that requires outdated `whatwg-url` package) is a polyfill for native fetch which is available in newer node versions,
I'd use it only when native fetch is not available.
