### ISSUE TITLE
Problem executing PUSH command

### ISSUE THREAD

**Issue by tomasalvarez13** [Redocly/redocly-cli#1424]
Hi, im having an issue using the `push` command. Im using this command inside a Bitbucket sumodule, and when i run the command locally from my terminal, it works as expected, but when i run exactly the same command inside the submodule, i get this error:

```
REDOCLY_AUTHORIZATION={my_api_key} redocly push --destination=prueba@v1 --organization=fpay:
No api found that matches prueba@v1. Please make sure you have provided the correct data in the config file.
```

I haven't made any changes to my code recently, it just stopped working yesterday.

**Comment by IgorKarpiuk** [comment]
Hello @tomasalvarez13 thanks for reporting.
We have just merged  [fix](https://github.com/Redocly/redocly-cli/pull/1419) and will release it soon

**Comment by tomasalvarez13** [comment]
Hi Igor! So this was actually a problem of redocly?

**Comment by IgorKarpiuk** [comment]
Yes, this is a problem with the `push` command

**Comment by tomasalvarez13** [comment]
Ok thanks! And is there any other way to execute this command successfully right now?

**Comment by IgorKarpiuk** [comment]
Yes, you should have `redocly.yaml` file in the root with the api that you want to push.
Something like this:
```yaml
apis:
  prueba@v1:
    root: path yo your file
```

**Comment by tomasalvarez13** [comment]
Ok thanks! I will try it

**Comment by IgorKarpiuk** [comment]
@tomasalvarez13 @lostinpatterns   Just released `1.8.2`.
Could you confirm that this has been fixed?

**Comment by tomasalvarez13** [comment]
@IgorKarpiuk Im still getting the same error. Im not using any config file (as allways). @lostinpatterns Does it works for you?

**Comment by IgorKarpiuk** [comment]
@tomasalvarez13 do you run command `redocly push --destination=prueba@v1 --organization=fpay:` ? looks like here you miss path to your file `redocly push <path to file> --destination=prueba@v1 --organization=fpay:`

**Comment by tomasalvarez13** [comment]
Oh sorry, with all the changes i made debbuging, y forgot to restore that one. Thanks Igor, i will try now

**Comment by tomasalvarez13** [comment]
@IgorKarpiuk It worked!! Thanks a lot!!

**Comment by lostinpatterns** [comment]
@IgorKarpiuk worked, thank you
