### ISSUE TITLE
Preview renders both source and output

### ISSUE THREAD

**Issue by javierjulio** [Redocly/redocly-cli#2347]
With redocly-cli v2 and now using multiple apis, I've noticed that the `redocly preview` command renders a navigation for both the source and output. 

Consider the following `redocly.yaml` config:

```
apis:
  cms@v1:
    root: ./cms/openapi.yaml
    output: ./cms-openapi.yml
  main@v1:
    root: ./main/openapi.yaml
    output: ./main-openapi.yml
# ...
ignore:
  - 'cms-openapi.yml'
  - 'main-openapi.yml'
  - '**/README.md'
```

In preview, assuming defaults, the navigation generated will have a collapsible area for both CMS and Main but at the top level it will also output each of the tags for both APIs when it's unexpected.

When reviewing the URL in the browser's address bar, anything within the "> cms" collapsible menu will have `/cms/...` in the URL suggesting it's rendering content from the api root directory. When it's a top level link, it's using `/cms-openapi/...` in the URL meaning that the Preview tool is using the bundled output for some reason.

I've tried setting an `ignore` list in the redocly config (as shown earlier) but it doesn't work as expected. Funny enough, I can ignore the `/cms` and `/main` directories but that feels like an odd workaround since it's the source that at least I expected to render.

When using the `redocly preview` command, is there a way to ignore the output files from being rendered in the preview site navigation?

**Comment by tatomyr** [comment]
What do you use the `output`s for?

**Comment by javierjulio** [comment]
I need to bundle each API as I have to commit the static file. The docs state that we can [specify the default output location for a bundled API in the apis section of a Redocly configuration file](https://redocly.com/docs/cli/commands/bundle#bundle-multiple-api-descriptions).

**Comment by tatomyr** [comment]
@javierjulio do you use different decorators for you apis? If not, you likely don't need the `output`s. You can run something like  the following: `redocly bundle cms/**/*.yaml -o bundled-apis/`.
Either way, the fix for ignoring the outputs is available in `@redocly/realm` (which is used for rendering the preview) under the `next` version tag. You can install it locally in your project and the `preview` command will use the installed version. If you prefer using the stable release, it will be available in a month or so.

**Comment by javierjulio** [comment]
@tatomyr I ran `npm install @redocly/realm@next` and confirmed that the next (0.127.0-next.1) release fixes the navigation rendering issue. Thank you. I don't use decorators. I'm using the `output`'s to configure the bundle file for each API in one place (redocly config) so the (single) bundle command runs without arguments. This way when I add a new API (going to add a third) it's all there and I don't have to update the package script with a bundle command for each API.

**Comment by tatomyr** [comment]
Great, @javierjulio. So, can we consider this issue resolved? 
BTW, a new stable Realm `v0.126.2` with the fix has been released today, so you can switch back to the latest version if you want.

**Comment by javierjulio** [comment]
@tatomyr no because I tried upgrading now `@redocly/cli` from 2.5.0 to 2.6.0 after removing `@redocly/realm` from my dependencies, ran `npm install` but the issue still persists with the stable Realm v0.126.2 release. Are you sure the change was included in v0.126.2? I see the 0.127.0-next.1 release is still available which is what I had installed and confirmed that it fixed the navigation issue.

**Comment by tatomyr** [comment]
I see, the fix wasn't included in the patch indeed. Let's wait for the stable release then. Sorry for the confusion!

**Comment by javierjulio** [comment]
@tatomyr there is a final @redocly/realm 0.127.0 release available now. I've confirmed the issue is still resolved on that release so all set here. Thank you again for your help! Much appreciated.
